version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: "postgres-aquarium"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "127.0.0.1:5432:5432"
  web:
    build: .
    container_name: "web-aquarium"
    ports:
      - "127.0.0.1:8000:8003"
    volumes:
      - .:/aquarium
    restart: unless-stopped
    env_file:
      - .env
